"""SQLite compatible migration

Revision ID: 002
Revises: 001
Create Date: 2025-09-19 13:40:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create patients table (SQLite compatible)
    op.create_table('patients',
        sa.Column('id', sa.Text(), nullable=False),  # UUID as TEXT in SQLite
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('phone_e164', sa.Text(), nullable=False),
        sa.Column('tags', sa.Text(), nullable=True),  # JSON as TEXT in SQLite
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone_e164')
    )
    
    # Create wa_campaigns table (SQLite compatible)
    op.create_table('wa_campaigns',
        sa.Column('id', sa.Text(), nullable=False),  # UUID as TEXT in SQLite
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('template_name', sa.Text(), nullable=False),
        sa.Column('lang_code', sa.Text(), nullable=False),
        sa.Column('params_mode', sa.Text(), nullable=False),
        sa.Column('fixed_params', sa.Text(), nullable=True),  # JSON as TEXT in SQLite
        sa.Column('tz', sa.Text(), nullable=False),
        sa.Column('start_at', sa.DateTime(), nullable=False),
        sa.Column('end_at', sa.DateTime(), nullable=True),
        sa.Column('frequency', sa.Text(), nullable=False),
        sa.Column('days_of_week', sa.Text(), nullable=True),  # Array as TEXT in SQLite
        sa.Column('day_of_month', sa.Integer(), nullable=True),
        sa.Column('send_time', sa.Text(), nullable=False),  # Time as TEXT in SQLite
        sa.Column('cron_expr', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create wa_campaign_recipients table (SQLite compatible)
    op.create_table('wa_campaign_recipients',
        sa.Column('campaign_id', sa.Text(), nullable=False),  # UUID as TEXT in SQLite
        sa.Column('phone_e164', sa.Text(), nullable=False),
        sa.Column('per_params', sa.Text(), nullable=True),  # JSON as TEXT in SQLite
        sa.ForeignKeyConstraint(['campaign_id'], ['wa_campaigns.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('campaign_id', 'phone_e164')
    )
    
    # Create wa_campaign_runs table (SQLite compatible)
    op.create_table('wa_campaign_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('campaign_id', sa.Text(), nullable=False),  # UUID as TEXT in SQLite
        sa.Column('run_at', sa.DateTime(), nullable=False),
        sa.Column('phone_e164', sa.Text(), nullable=False),
        sa.Column('payload', sa.Text(), nullable=True),  # JSON as TEXT in SQLite
        sa.Column('wa_response', sa.Text(), nullable=True),  # JSON as TEXT in SQLite
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['wa_campaigns.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('idx_patients_phone', 'patients', ['phone_e164'])
    op.create_index('idx_patients_active', 'patients', ['active'])
    op.create_index('idx_campaigns_status', 'wa_campaigns', ['status'])
    op.create_index('idx_campaigns_frequency', 'wa_campaigns', ['frequency'])
    op.create_index('idx_campaigns_start_at', 'wa_campaigns', ['start_at'])
    op.create_index('idx_campaign_runs_campaign_id', 'wa_campaign_runs', ['campaign_id'])
    op.create_index('idx_campaign_runs_run_at', 'wa_campaign_runs', ['run_at'])
    op.create_index('idx_campaign_runs_status', 'wa_campaign_runs', ['status'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_campaign_runs_status')
    op.drop_index('idx_campaign_runs_run_at')
    op.drop_index('idx_campaign_runs_campaign_id')
    op.drop_index('idx_campaigns_start_at')
    op.drop_index('idx_campaigns_frequency')
    op.drop_index('idx_campaigns_status')
    op.drop_index('idx_patients_active')
    op.drop_index('idx_patients_phone')
    
    # Drop tables
    op.drop_table('wa_campaign_runs')
    op.drop_table('wa_campaign_recipients')
    op.drop_table('wa_campaigns')
    op.drop_table('patients')
    
    # ### end Alembic commands ###
