name: ci
on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Syntax gate (compileall)
        run: |
          python - << 'PY'
          import compileall, sys
          ok = compileall.compile_dir(".", maxlevels=10, quiet=1)
          sys.exit(0 if ok else 1)
          PY
